name: Java CI with Maven

on:
  workflow_dispatch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

# env:
#   DEPLOYMENT_PATH_NAME: deployment_artifact

jobs:
  build:
    runs-on: tomcat-server
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml -DskipITs --settings ./maven/settings.xml -DskipTests
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        # Artifact name
        name: myshuttle
        # A file, directory, or wildcard pattern that describes what to upload
        path: "/home/ubuntu/actions-runner/_work/Java-Application/Java-Application/target/myshuttledev.war"
