name: Deploy
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
jobs:
  Dev:      
      runs-on: deployment_server
      environment: Dev
      # To set environment variables at the job level and reference them using ${{env.variablename}}
      # env:
      #   DEPLOYMENT_PATH_NAME: deployment_artifact
        
      steps:            
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
            script: |
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
              });
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "myshuttle"
              })[0];
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/myshuttle.zip`, Buffer.from(download.data));

        - name: 'Unzip artifact'
          run: unzip myshuttle.zip
            
        # - name: Deploy the build artifact to the Tomcat server
        #   run: sudo cp $GITHUB_WORKSPACE/${{vars.DEPLOYMENT_PATH_NAME}}/myshuttledev.war /var/lib/tomcat9/webapps
