name: Dev Environment

on:
  # push:
  #   branches: [master]
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  Dev:
    runs-on: dev-server
    environment: Dev
    steps:
      - uses: ./.github/workflows/reusable-workflow-deploy.yml
        # with:
        #   runner_label: dev-server
        
