# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: #workflow_dispatch
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:
  build:

    runs-on: tomcat-server

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml -DskipITs --settings ./maven/settings.xml -DskipTests

    - name: Check files in the agent folder
      run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -al
          cd target
          ls -al
          pwd
          cp $GITHUB_WORKSPACE/target/myshuttledev.war /home/ubuntu/temp
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        # Artifact name
        name: myshuttle
        # A file, directory or wildcard pattern that describes what to upload
        path: "/home/ubuntu/actions-runner/_work/Java-Application/Java-Application/target/myshuttledev.war"

    - name: Deploy the build artifact to the tomcat server
      run: cp $GITHUB_WORKSPACE/target/myshuttledev.war /opt/tomcat/webapps

    
